# Generated by Django 3.2.13 on 2022-07-13 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Subject', models.CharField(max_length=150)),
                ('Message', models.TextField(max_length=150)),
                ('Date_submit', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
